trigger:
  - master
pool:
  vmImage: "windows-latest"

variables:
  BuildConfiguration: "Release"
  BuildPlatform: "Any CPU"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
      includePreviewVersions: true
      
  - task: DotNetCoreCLI@2
    displayName: "Restore"
    inputs:
      command: restore
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: build
      projects: "**/*.csproj"
      configuration: "$(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --collect "Code Coverage" -f "net5.0" -s "src/test.runsettings"'